[build]
target = "../avr-specs/avr-atmega328p.json"
rustflags = ["-C", "target-cpu=atmega328p"]

[unstable]
build-std = ["core", "alloc"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[target.'cfg(all())']
runner = ["avrdude", "-v", "-patmega328p", "-carduino", "-P/dev/cu.usbserial-210", "-D", "-Uflash:w:target/avr-atmega328p/release/epworth-organ-encoder-avr.elf:e"]
