#![no_std]
#![no_main]

mod debouncer;
mod events;
mod mcp23017;
mod presets;

use core::cell::RefCell;

use debouncer::Debouncer;
use embassy_embedded_hal::shared_bus::blocking::i2c::I2cDevice;
use embassy_executor::Spawner;
use embassy_rp::flash::Flash;
use embassy_rp::gpio::Pull;
use embassy_rp::peripherals::{I2C0, UART0, USB};
use embassy_rp::{
    Peri,
    gpio::{AnyPin, Input, Level, Output},
};
use embassy_rp::{bind_interrupts, i2c};
use embassy_rp::{uart, usb};
use embassy_sync::blocking_mutex::Mutex;
use embassy_sync::blocking_mutex::raw::{CriticalSectionRawMutex, NoopRawMutex};
use embassy_sync::channel::Channel;
use embassy_sync::signal::Signal;
use embassy_time::Timer;
use embassy_usb::class::midi::MidiClass;
use embassy_usb::{Builder, Config as UsbConfig};
use midly::MidiMessage;
use midly::live::LiveEvent;
use midly::num::{u4, u7};
use panic_halt as _;
use static_cell::{ConstStaticCell, StaticCell};

use crate::events::{Event, EventIn, EventSource};
use crate::mcp23017::MCP23017;
use crate::mcp23017::Port;
use crate::presets::PresetStore;

type I2c0Bus = Mutex<NoopRawMutex, RefCell<i2c::I2c<'static, I2C0, i2c::Blocking>>>;
type I2c0Mcp = MCP23017<I2cDevice<'static, NoopRawMutex, i2c::I2c<'static, I2C0, i2c::Blocking>>>;

bind_interrupts!(struct Irqs {
    USBCTRL_IRQ => usb::InterruptHandler<USB>;
    UART0_IRQ => uart::InterruptHandler<UART0>;
});

const B: [u32; 4] = [0x55555555, 0x33333333, 0x0F0F0F0F, 0x00FF00FF];
const S: [u32; 4] = [1, 2, 4, 8];
const NIBBLE_REVERSE_LOOKUP: [u8; 16] = [
    0x0, 0x8, 0x4, 0xc, 0x2, 0xa, 0x6, 0xe, 0x1, 0x9, 0x5, 0xd, 0x3, 0xb, 0x7, 0xf,
];

static STOP_STATE: Signal<CriticalSectionRawMutex, u64> = Signal::new();
static PRESET_STORE: StaticCell<PresetStore> = StaticCell::new();

// Queue for all events on the organ. These events can be either generated by mechanical interactions with the console
// (e.g. pressing a stop tab button, moving an expression pedal, etc.) or received over USB.
static MAIN_EVENT_BUS: Channel<CriticalSectionRawMutex, EventIn, 128> = Channel::new();

// This channel has a relatively large buffer to accommodate bursts of MIDI messages when recalling presets. If the USB
// host is slow or disconnected (e.g. in analog-only mode), we don't want to block the entire system.
static OUTBOUND_USB_MIDI_EVENT_BUS: Channel<CriticalSectionRawMutex, LiveEvent, 128> =
    Channel::new();

static USB_CONFIG_DESCRIPTOR: ConstStaticCell<[u8; 256]> = ConstStaticCell::new([0; 256]);
static USB_BOS_DESCRIPTOR: ConstStaticCell<[u8; 256]> = ConstStaticCell::new([0; 256]);
static USB_CONTROL_BUF: ConstStaticCell<[u8; 64]> = ConstStaticCell::new([0; 64]);

fn reverse_byte(a: &u8) -> u8 {
    let mut b = *a;
    b = (b & 0xF0) >> 4 | (b & 0x0F) << 4;
    b = (b & 0xCC) >> 2 | (b & 0x33) << 2;
    b = (b & 0xAA) >> 1 | (b & 0x55) << 1;
    b
}

fn interleave_bits(a: u16, b: u16) -> u32 {
    let mut x = a as u32;
    let mut y = b as u32;

    for i in (0..4).rev() {
        x = (x | (x << S[i])) & B[i];
        y = (y | (y << S[i])) & B[i];
    }
    x | (y << 1)
}

fn stop_tab_midi_cc_message(div: usize, i: u8, div_stop_state: u16) -> LiveEvent<'static> {
    let mut midi_val: u7 = 0.into();
    if div_stop_state >> i & 1 == 1 {
        midi_val = u7::max_value();
    }
    LiveEvent::Midi {
        channel: u4::from(div as u8),
        message: MidiMessage::Controller {
            controller: (117 - i).into(),
            value: midi_val,
        },
    }
}

fn get_mcps(i2c_bus: &'static I2c0Bus) -> [[I2c0Mcp; 2]; 4] {
    [[0x20, 0x21], [0x22, 0x23], [0x24, 0x25], [0x26, 0x27]].map(|[addr0, addr1]| {
        [
            MCP23017::new(I2cDevice::new(i2c_bus), addr0),
            MCP23017::new(I2cDevice::new(i2c_bus), addr1),
        ]
    })
}

// TODO: Pack all the pins into a struct? It's too unwieldy right now.
#[embassy_executor::task]
async fn flush_stop_state(
    i2c_bus: &'static I2c0Bus,
    data_pin: Peri<'static, AnyPin>,
    clock_pin: Peri<'static, AnyPin>,
    latch_pin: Peri<'static, AnyPin>,
    oe_pin: Peri<'static, AnyPin>,
) {
    let mcps = &mut get_mcps(i2c_bus);
    let mut stops_data_pin = Output::new(data_pin, Level::Low);
    let mut stops_clock_pin = Output::new(clock_pin, Level::Low);
    let mut stops_latch_pin = Output::new(latch_pin, Level::Low);
    let mut stops_oe_pin = Output::new(oe_pin, Level::High);

    stops_oe_pin.set_low();

    loop {
        // Only update when things have changed.
        let mut stop_state: u64 = STOP_STATE.wait().await;

        // This is our approach to batching lots of little changes: Wait for a brief interval before reading the stop
        // states.
        Timer::after_millis(1).await;

        stop_state = STOP_STATE.try_take().or(Some(stop_state)).unwrap();

        let left_half = interleave_bits(
            (stop_state >> 16 & 0xFFFF) as u16,
            (stop_state >> 32 & 0xFFFF) as u16,
        );
        let right_half = interleave_bits(
            (stop_state >> 48 & 0xFFFF) as u16,
            (stop_state & 0xFFFF) as u16,
        );

        for val in [right_half, left_half] {
            for i in 0..4 {
                let mut to_write = ((val >> (8 * i)) & 0xFF) as u8;
                // Reverse lower nibble
                to_write = (to_write & 0xF0) | NIBBLE_REVERSE_LOOKUP[(to_write & 0x0F) as usize];

                // Manual ShiftOut
                for bit in 0..8 {
                    if (to_write >> bit) & 1 == 1 {
                        stops_data_pin.set_high();
                    } else {
                        stops_data_pin.set_low();
                    }
                    stops_clock_pin.set_high();
                    stops_clock_pin.set_low();
                }
            }
        }

        stops_latch_pin.set_high();
        stops_latch_pin.set_low();

        // Second (as it's slightly less important), flush state to the LEDs on the MCP23017s.
        for div in 0..4 {
            let state = stop_state >> (16 * div) & 0xFFFF;
            let left_half = reverse_byte(&(!(state >> 8) as u8));
            let right_half = reverse_byte(&(!(state & 0xFF) as u8));
            mcps[div][0]
                .write_gpio(Port::GPIOA, (left_half & 0x7F) << 1)
                .unwrap();
            mcps[div][0]
                .write_gpio(Port::GPIOB, left_half & 0x80)
                .unwrap();
            mcps[div][1]
                .write_gpio(Port::GPIOA, right_half & 0x7F)
                .unwrap();
        }
    }
}

#[embassy_executor::task]
async fn scan_stop_tab_buttons(i2c_bus: &'static I2c0Bus) {
    let mut mcps = get_mcps(i2c_bus);
    let mut stop_tab_button_debouncers: [Debouncer<5>; 4] = [
        Debouncer::<5>::new(0xFFFF),
        Debouncer::<5>::new(0xFFFF),
        Debouncer::<5>::new(0xFFFF),
        Debouncer::<5>::new(0xFFFF),
    ];

    loop {
        for (div, mcp_pair) in mcps.iter_mut().enumerate() {
            let mut raw_reading = 0x01u16; // LSB always 1, by convention
            raw_reading |= ((mcp_pair[0].read_gpio(Port::GPIOA).unwrap() & 0x01) as u16) << 8;
            raw_reading |= ((mcp_pair[0].read_gpio(Port::GPIOB).unwrap() & 0x7F) as u16) << 9;
            raw_reading |= ((mcp_pair[1].read_gpio(Port::GPIOB).unwrap() & 0x7F) as u16) << 1;
            stop_tab_button_debouncers[div].update(raw_reading);

            for i in stop_tab_button_debouncers[div].falling_edges() {
                MAIN_EVENT_BUS
                    .send(EventIn(
                        EventSource::Local,
                        Event::StopToggle(div.into(), i),
                    ))
                    .await;
            }
        }
        Timer::after_micros(200).await;
    }
}

#[embassy_executor::task]
async fn scan_pistons(
    load_pin: Peri<'static, AnyPin>,
    clock_pin: Peri<'static, AnyPin>,
    data_pin: Peri<'static, AnyPin>,
) {
    let mut piston_debouncer = Debouncer::<5>::new(0xFFFF);

    // Load piston states into 74HC165 shift register
    let mut piston_load_pin = Output::new(load_pin, Level::Low);
    let mut piston_clock_pin = Output::new(clock_pin, Level::Low);
    let piston_data_pin = Input::new(data_pin, Pull::Up);

    loop {
        piston_load_pin.set_low();
        piston_load_pin.set_high();

        let mut raw_piston_reading = 0u16;
        // Ensure clock pin low first...
        piston_clock_pin.set_low();

        // ...then clock the data into the piston readings.
        for i in 0..8 {
            if piston_data_pin.is_high() {
                raw_piston_reading |= 1 << i;
            }
            piston_clock_pin.set_high();
            piston_clock_pin.set_low();
        }
        // Nothing is hooked up to 8-15 right now...
        raw_piston_reading |= 0xFF00;

        piston_debouncer.update(raw_piston_reading);

        for i in piston_debouncer.falling_edges() {
            if i == 0 {
                MAIN_EVENT_BUS
                    .send(EventIn(EventSource::Local, Event::EnableSave(true)))
                    .await;
            } else if i == 1 {
                MAIN_EVENT_BUS
                    .send(EventIn(EventSource::Local, Event::GeneralCancel()))
                    .await;
            } else {
                MAIN_EVENT_BUS
                    .send(EventIn(EventSource::Local, Event::RecallPreset(i)))
                    .await;
            }
        }

        for i in piston_debouncer.rising_edges() {
            if i == 0 {
                MAIN_EVENT_BUS
                    .send(EventIn(EventSource::Local, Event::EnableSave(false)))
                    .await;
            }
        }

        Timer::after_micros(200).await;
    }
}

#[embassy_executor::task]
async fn run_usb_device(
    mut usb_device: embassy_usb::UsbDevice<'static, usb::Driver<'static, USB>>,
) {
    usb_device.run().await;
}

#[embassy_executor::task]
async fn usb_midi_driver(spawner: Spawner, usb: Peri<'static, USB>) {
    let driver = usb::Driver::new(usb, Irqs);
    let mut config = UsbConfig::new(0xc0de, 0xcafe);
    config.manufacturer = Some("RP Pico 2");
    config.product = Some("Epworth Organ MIDI");
    config.serial_number = Some("12345678");
    config.max_power = 100;
    config.max_packet_size_0 = 64;

    let mut builder = Builder::new(
        driver,
        config,
        USB_CONFIG_DESCRIPTOR.take(),
        USB_BOS_DESCRIPTOR.take(),
        &mut [], // no msos descriptors
        USB_CONTROL_BUF.take(),
    );

    let mut midi_class = MidiClass::new(&mut builder, 1, 1, 64);

    // Build the builder.
    let usb_device = builder.build();

    // Run the USB device forever, in a separate task.
    spawner.spawn(run_usb_device(usb_device)).unwrap();

    midi_class.wait_connection().await;

    loop {
        let event = OUTBOUND_USB_MIDI_EVENT_BUS.receive().await;

        let midi_data: [u8; 4] = match event {
            LiveEvent::Midi { channel, message } => match message {
                MidiMessage::Controller { controller, value } => [
                    0x0B,
                    channel.as_int() | 0xB0,
                    controller.as_int(),
                    value.as_int(),
                ],
                _ => [0x00; 4],
            },
            _ => [0x00; 4],
        };
        let _ = midi_class.write_packet(&midi_data).await;
    }
}

#[embassy_executor::task]
async fn uart_reader(mut uart_rx: uart::UartRx<'static, uart::Async>) {
    loop {
        // All events on UART are proprietary 2-byte messages, as defined in the Event struct.
        let mut buf: [u8; 2] = [0; 2];

        match uart_rx.read(&mut buf).await {
            Ok(_) => {
                MAIN_EVENT_BUS
                    .send(EventIn(EventSource::Local, Event::parse(buf[0], buf[1])))
                    .await;
            }
            Err(e) => {
                defmt::warn!("Error reading from UART: {:?}", e);
            }
        }
    }
}

fn setup_mcps(i2c_bus: &'static I2c0Bus) {
    for mcp_pair in get_mcps(i2c_bus).iter_mut() {
        mcp_pair[0].init_hardware().unwrap();
        mcp_pair[1].init_hardware().unwrap();
        // Set pin modes (input/output) for MCP23017s based on the schematic
        mcp_pair[0].port_mode(Port::GPIOA, 0x01).unwrap();
        mcp_pair[0].port_mode(Port::GPIOB, 0x7F).unwrap();
        mcp_pair[1].port_mode(Port::GPIOA, 0x00).unwrap();
        mcp_pair[1].port_mode(Port::GPIOB, 0x7F).unwrap();
        // Write all outputs high, inputs low.
        mcp_pair[0].write_gpio(Port::GPIOA, 0xFE).unwrap();
        mcp_pair[0].write_gpio(Port::GPIOB, 0x80).unwrap();
        mcp_pair[1].write_gpio(Port::GPIOA, 0x7F).unwrap();
        mcp_pair[1].write_gpio(Port::GPIOB, 0x00).unwrap();
    }
}

#[embassy_executor::task]
async fn main_event_handler(preset_store: &'static mut PresetStore<'static>) {
    // TODO: I think we need a dedicated class to store all this state and compute events resulting from the combination
    // of incoming events and current state, e.g. interaction between notes and couplers or whether to send stop on or
    // off based on an incoming toggle.
    let mut stop_state: u64 = 0u64;
    let mut awaiting_save = false;

    // Flush initial stop state.
    STOP_STATE.signal(stop_state);

    loop {
        let event_in = MAIN_EVENT_BUS.receive().await;

        match event_in.1 {
            Event::StopToggle(div, idx) => {
                // TODO: This is insufficient. Toggling a stop may produce NoteOn or NoteOff events, too! We need to
                // abstract this away into a pure business logic class that handles all that.
                stop_state ^= 1 << (16 * div as u8 + idx);
                STOP_STATE.signal(stop_state);
                let div_stop_state = (stop_state >> (16 * div as u8) & 0xFFFF) as u16;
                let msg = stop_tab_midi_cc_message(div.into(), idx, div_stop_state);
                let _ = OUTBOUND_USB_MIDI_EVENT_BUS.try_send(msg);
            }
            Event::GeneralCancel() => {
                stop_state = 0;
                STOP_STATE.signal(stop_state);
                // TODO: All sorts of MIDI messages. GC, "AllNotesOff", etc.
            }
            Event::RecallPreset(idx) => {
                if awaiting_save {
                    // Saving a preset is completely internal; it emits no MIDI events.
                    preset_store.save(idx, &stop_state).await;
                } else {
                    // Recalling a preset, on the other hand, emits a program change.
                    let program_change = LiveEvent::Midi {
                        channel: 5.into(),
                        message: MidiMessage::ProgramChange {
                            program: idx.into(),
                        },
                    };
                    let _ = OUTBOUND_USB_MIDI_EVENT_BUS.try_send(program_change);
                    stop_state = preset_store.load(idx).await;
                    STOP_STATE.signal(stop_state);
                    for div in 0..4 {
                        let div_state = ((stop_state >> (16 * div)) & 0xFFFF) as u16;
                        // Now we need to emit 15 MIDI CCs...skipping i = 0 (LSB) which doesn't correspond to physical hardware
                        for i in 1..=15 {
                            let msg = stop_tab_midi_cc_message(div, i, div_state);
                            let _ = OUTBOUND_USB_MIDI_EVENT_BUS.try_send(msg); // yes, yes, this could return error
                        }
                    }
                }
            }
            Event::EnableSave(val) => {
                awaiting_save = val;
            }
            _ => {}
        }
    }
}

#[embassy_executor::main]
async fn main(spawner: Spawner) {
    let p = embassy_rp::init(Default::default());

    let i2c = embassy_rp::i2c::I2c::new_blocking(p.I2C0, p.PIN_5, p.PIN_4, i2c::Config::default());
    static I2C_BUS: StaticCell<I2c0Bus> = StaticCell::new();
    let i2c_bus = I2C_BUS.init(Mutex::new(i2c.into()));

    spawner
        .spawn(main_event_handler(
            PRESET_STORE.init(PresetStore::new(Flash::new(p.FLASH, p.DMA_CH2))),
        ))
        .unwrap();

    let uart_txrx = uart::Uart::new(
        p.UART0,
        p.PIN_16,
        p.PIN_17,
        Irqs,
        p.DMA_CH0,
        p.DMA_CH1,
        uart::Config::default(),
    );
    let (_, uart_rx) = uart_txrx.split();
    spawner.spawn(uart_reader(uart_rx)).unwrap();

    setup_mcps(i2c_bus);
    spawner.spawn(scan_stop_tab_buttons(i2c_bus)).unwrap();
    spawner
        .spawn(flush_stop_state(
            i2c_bus,
            p.PIN_21.into(),
            p.PIN_19.into(),
            p.PIN_20.into(),
            p.PIN_18.into(),
        ))
        .unwrap();
    spawner
        .spawn(scan_pistons(
            p.PIN_11.into(),
            p.PIN_12.into(),
            p.PIN_13.into(),
        ))
        .unwrap();
    spawner.spawn(usb_midi_driver(spawner, p.USB)).unwrap();

    // Heartbeat task comes last, and happens on the main loop, roughly indicating that all tasks spawned successfully.
    let mut led = Output::new(p.PIN_25, Level::Low);

    loop {
        led.toggle();
        Timer::after_secs(1).await;
    }
}
