#![no_std]
#![no_main]

mod mcp23017;
mod presets;
mod usb;

use embassy_sync::signal::Signal;
use panic_probe as _;

use core::cell::RefCell;

use embassy_embedded_hal::shared_bus::blocking::i2c::I2cDevice;
use embassy_executor::Spawner;
use embassy_rp::flash::Flash;
use embassy_rp::gpio::{AnyPin, Input, Level, Output, Pull};
use embassy_rp::peripherals::{I2C0, UART0, USB};
use embassy_rp::{Peri, bind_interrupts, i2c, uart, usb as rp_usb};
use embassy_sync::blocking_mutex::Mutex;
use embassy_sync::blocking_mutex::raw::{CriticalSectionRawMutex, NoopRawMutex};
use embassy_sync::channel::Channel;
use embassy_time::Timer;
use embassy_usb::class::midi as usb_midi;
use embassy_usb::class::midi::MidiClass;
use embassy_usb::{Builder as UsbBuilder, Config as UsbConfig};
use embedded_io_async::{Read, Write};
use epworth_organ::Division;
use epworth_organ::command::{Command, CommandSource};
use epworth_organ::debouncer::Debouncer;
use epworth_organ::event::Event;
use postcard::{from_bytes_cobs, to_slice_cobs};
use static_cell::{ConstStaticCell, StaticCell};

use crate::mcp23017::MCP23017;
use crate::mcp23017::Port;
use crate::presets::PresetStore;
use crate::usb::UsbWritable;

type I2c0Bus = Mutex<NoopRawMutex, RefCell<i2c::I2c<'static, I2C0, i2c::Blocking>>>;
type I2c0Mcp = MCP23017<I2cDevice<'static, NoopRawMutex, i2c::I2c<'static, I2C0, i2c::Blocking>>>;

bind_interrupts!(struct Irqs {
    USBCTRL_IRQ => rp_usb::InterruptHandler<USB>;
    UART0_IRQ => uart::BufferedInterruptHandler<UART0>;
});

const MCP_I2C_ADDRESSES: [[u8; 2]; 4] = [[0x20, 0x21], [0x22, 0x23], [0x24, 0x25], [0x26, 0x27]];
const DIVISIONS: [Division; 4] = [
    Division::Swell,
    Division::Great,
    Division::Choir,
    Division::Pedal,
];

static LATEST_STOP_STATE: Signal<CriticalSectionRawMutex, u64> = Signal::new();
static PRESET_STORE: StaticCell<PresetStore> = StaticCell::new();

// Queue for all commands on the organ. These commands can be either generated by mechanical interactions with the
// console (e.g. pressing a stop tab button, moving an expression pedal, etc.), including mechanical interactions
// relayed to this particular MCU over UART, or they can be received over USB MIDI.
static COMMANDS: Channel<CriticalSectionRawMutex, (Command, CommandSource), 8> = Channel::new();

// Queues for events destined for the decoders (via UART) or the computer (via USB).
static UART_EVENTS: Channel<CriticalSectionRawMutex, Event, 8> = Channel::new();
static USB_EVENTS: Channel<CriticalSectionRawMutex, Event, 8> = Channel::new();

static USB_CONFIG_DESCRIPTOR: ConstStaticCell<[u8; 512]> = ConstStaticCell::new([0; 512]);
static USB_BOS_DESCRIPTOR: ConstStaticCell<[u8; 256]> = ConstStaticCell::new([0; 256]);
static USB_CONTROL_BUF: ConstStaticCell<[u8; 128]> = ConstStaticCell::new([0; 128]);

fn reverse_byte(a: &u8) -> u8 {
    let mut b = *a;
    b = (b & 0xF0) >> 4 | (b & 0x0F) << 4;
    b = (b & 0xCC) >> 2 | (b & 0x33) << 2;
    b = (b & 0xAA) >> 1 | (b & 0x55) << 1;
    b
}

fn get_mcps(i2c_bus: &'static I2c0Bus) -> [[I2c0Mcp; 2]; 4] {
    MCP_I2C_ADDRESSES.map(|[addr0, addr1]| {
        [
            MCP23017::new(I2cDevice::new(i2c_bus), addr0),
            MCP23017::new(I2cDevice::new(i2c_bus), addr1),
        ]
    })
}

#[embassy_executor::task]
async fn write_stop_state_to_leds(i2c_bus: &'static I2c0Bus) {
    let mcp_pairs = &mut get_mcps(i2c_bus);

    loop {
        let mut stop_state: u64 = LATEST_STOP_STATE.wait().await;

        // This is our approach to batching lots of little changes: Wait for a brief interval before reading the stop
        // states again.
        Timer::after_millis(1).await;

        stop_state = LATEST_STOP_STATE.try_take().unwrap_or(stop_state);

        for (mcp_pair, div) in mcp_pairs.iter_mut().zip(DIVISIONS) {
            let state = stop_state >> (16 * div as u8) & 0xFFFF;
            let left_half = reverse_byte(&(!(state >> 8) as u8));
            let right_half = reverse_byte(&(!(state & 0xFF) as u8));
            mcp_pair[0]
                .write_gpio(Port::GPIOA, (left_half & 0x7F) << 1)
                .unwrap();
            mcp_pair[0]
                .write_gpio(Port::GPIOB, left_half & 0x80)
                .unwrap();
            mcp_pair[1]
                .write_gpio(Port::GPIOA, right_half & 0x7F)
                .unwrap();
        }
    }
}

#[embassy_executor::task]
async fn scan_stop_tab_buttons(i2c_bus: &'static I2c0Bus) {
    let mut mcp_pairs = get_mcps(i2c_bus);
    let mut stop_tab_button_debouncers: [Debouncer<5>; 4] = [
        Debouncer::<5>::new(0xFFFF),
        Debouncer::<5>::new(0xFFFF),
        Debouncer::<5>::new(0xFFFF),
        Debouncer::<5>::new(0xFFFF),
    ];

    loop {
        for (mcp_pair, div) in mcp_pairs.iter_mut().zip(DIVISIONS) {
            let mut raw_reading = 0x01u16; // LSB always 1, by convention
            raw_reading |= ((mcp_pair[0].read_gpio(Port::GPIOA).unwrap() & 0x01) as u16) << 8;
            raw_reading |= ((mcp_pair[0].read_gpio(Port::GPIOB).unwrap() & 0x7F) as u16) << 9;
            raw_reading |= ((mcp_pair[1].read_gpio(Port::GPIOB).unwrap() & 0x7F) as u16) << 1;
            stop_tab_button_debouncers[div as usize].update(raw_reading);

            for i in stop_tab_button_debouncers[div as usize].falling_edges() {
                COMMANDS
                    .send((Command::StopToggle(div, i), CommandSource::Local))
                    .await;
            }
        }
        Timer::after_micros(500).await;
    }
}

#[embassy_executor::task]
async fn scan_pistons(
    load_pin: Peri<'static, AnyPin>,
    clock_pin: Peri<'static, AnyPin>,
    data_pin: Peri<'static, AnyPin>,
) {
    let mut piston_debouncer = Debouncer::<5>::new(0xFFFF);

    // Load piston states into 74HC165 shift register
    let mut piston_load_pin = Output::new(load_pin, Level::Low);
    let mut piston_clock_pin = Output::new(clock_pin, Level::Low);
    let piston_data_pin = Input::new(data_pin, Pull::Up);

    loop {
        piston_load_pin.set_low();
        piston_load_pin.set_high();

        let mut raw_piston_reading = 0u16;
        // Ensure clock pin low first...
        piston_clock_pin.set_low();

        // ...then clock the data into the piston readings.
        for i in 0..8 {
            if piston_data_pin.is_high() {
                raw_piston_reading |= 1 << i;
            }
            piston_clock_pin.set_high();
            piston_clock_pin.set_low();
        }
        // Nothing is hooked up to 8-15 right now...
        raw_piston_reading |= 0xFF00;

        piston_debouncer.update(raw_piston_reading);

        for i in piston_debouncer.falling_edges() {
            if i == 0 {
                COMMANDS
                    .send((Command::EnableSave(true), CommandSource::Local))
                    .await;
            } else if i == 1 {
                COMMANDS
                    .send((Command::GeneralCancel(), CommandSource::Local))
                    .await;
            } else {
                COMMANDS
                    .send((Command::RecallPreset(i), CommandSource::Local))
                    .await;
            }
        }

        for i in piston_debouncer.rising_edges() {
            if i == 0 {
                COMMANDS
                    .send((Command::EnableSave(false), CommandSource::Local))
                    .await;
            }
        }

        Timer::after_micros(500).await;
    }
}

#[embassy_executor::task]
async fn usb_midi_writer(mut usb_midi_tx: usb_midi::Sender<'static, rp_usb::Driver<'static, USB>>) {
    // TODO: Handle the case where the USB cable gets connected/disconnected while the program is running.
    // We can probably implement this by breaking out of the inner loop if we time out when writing packets.
    usb_midi_tx.wait_connection().await;

    loop {
        let event = USB_EVENTS.receive().await;
        event.write_to_usb(&mut usb_midi_tx).await;
    }
}

// TODO: I can't for the life of me get this working! The device just doesn't show up as writeable.
#[embassy_executor::task]
async fn usb_midi_reader(
    mut usb_midi_rx: usb_midi::Receiver<'static, rp_usb::Driver<'static, USB>>,
) {
    // TODO: Handle the case where the USB cable gets connected/disconnected while the program is running.
    usb_midi_rx.wait_connection().await;

    // let mut data = [0u8; 64];

    // loop {
    //     match usb_midi_rx.read_packet(&mut data).await {
    //         Ok(n) => {
    //             defmt::debug!("Got {:?} bytes", n);
    //             // Could there be multiple?
    //             let cmd = parse_command(&data[..n]);
    //             COMMANDS.send((cmd, CommandSource::External)).await;
    //         }
    //         Err(_) => {
    //             defmt::error!("Error reading USB MIDI");
    //             break;
    //         }
    //     }
    // }
}

#[embassy_executor::task]
async fn usb_midi(spawner: Spawner, usb: Peri<'static, USB>) {
    let driver = rp_usb::Driver::new(usb, Irqs);
    let mut config = UsbConfig::new(0xc0de, 0xcafe);
    config.manufacturer = Some("RP Pico 2");
    config.product = Some("Epworth Organ MIDI");
    config.serial_number = Some("12345678");
    config.max_power = 100;
    config.max_packet_size_0 = 64;

    let mut builder = UsbBuilder::new(
        driver,
        config,
        USB_CONFIG_DESCRIPTOR.take(),
        USB_BOS_DESCRIPTOR.take(),
        &mut [], // no msos descriptors
        USB_CONTROL_BUF.take(),
    );

    let midi_class = MidiClass::new(&mut builder, 1, 1, 64);

    // Build the builder.
    let mut usb_device = builder.build();

    let (usb_midi_tx, usb_midi_rx) = midi_class.split();

    spawner.spawn(usb_midi_writer(usb_midi_tx)).unwrap();
    spawner.spawn(usb_midi_reader(usb_midi_rx)).unwrap();

    // Run the USB device forever.
    loop {
        usb_device.run().await;
    }
}

#[embassy_executor::task]
async fn uart_reader(mut uart_rx: uart::BufferedUartRx) {
    loop {
        let mut buf: [u8; 64] = [0; 64];
        let _ = uart_rx.read(&mut buf).await;
        let res: Result<Command, _> = from_bytes_cobs(&mut buf);
        match res {
            Ok(cmd) => {
                COMMANDS.send((cmd, CommandSource::Local)).await;
            }
            Err(_) => {
                defmt::error!("Could not parse command on UART RX")
            }
        }
    }
}

#[embassy_executor::task]
async fn uart_writer(mut uart_tx: uart::BufferedUartTx) {
    loop {
        let event = UART_EVENTS.receive().await;
        // We have to be careful here about buffer size! Preset recall serializes to 12 bytes in my testing. I'm
        // leaving a few extra just in case i introduce anything around that size.
        let mut buf = [0u8; 64];
        let written = to_slice_cobs(&event, &mut buf).unwrap();
        let _ = uart_tx.write(written).await;
    }
}

fn setup_mcps(i2c_bus: &'static I2c0Bus) {
    for mcp_pair in get_mcps(i2c_bus).iter_mut() {
        mcp_pair[0].init_hardware().unwrap();
        mcp_pair[1].init_hardware().unwrap();
        // Set pin modes (input/output) for MCP23017s based on the schematic
        mcp_pair[0].port_mode(Port::GPIOA, 0x01).unwrap();
        mcp_pair[0].port_mode(Port::GPIOB, 0x7F).unwrap();
        mcp_pair[1].port_mode(Port::GPIOA, 0x00).unwrap();
        mcp_pair[1].port_mode(Port::GPIOB, 0x7F).unwrap();
        // Write all outputs high, inputs low.
        mcp_pair[0].write_gpio(Port::GPIOA, 0xFE).unwrap();
        mcp_pair[0].write_gpio(Port::GPIOB, 0x80).unwrap();
        mcp_pair[1].write_gpio(Port::GPIOA, 0x7F).unwrap();
        mcp_pair[1].write_gpio(Port::GPIOB, 0x00).unwrap();
    }
}

#[embassy_executor::task]
async fn main_event_handler(preset_store: &'static mut PresetStore<'static>) {
    let mut stop_state: u64 = 0u64;
    let mut awaiting_save = false;

    // Flush initial stop state.
    LATEST_STOP_STATE.signal(stop_state);

    loop {
        let (command, src) = COMMANDS.receive().await;

        // This is the guts of the primary encoder MCU. All commands issued to the organ go through this event loop in
        // order to affect any state on the organ. Some commands pass through essentially untouched to the decoder,
        // while others may result in numerous or even zero outbound events. This first match applies state-related
        // logic to incoming encoder commands (e.g. "toggle" messages converted to "on" or "off" depending on state).
        let event = match command {
            Command::NoteOff(div, value) => Some(Event::NoteOff(div, value)),
            Command::NoteOn(div, value) => Some(Event::NoteOn(div, value)),
            Command::StopOff(div, idx) => {
                stop_state &= !(1 << 16 * div as u8 + idx);
                LATEST_STOP_STATE.signal(stop_state);
                Some(Event::StopOff(div, idx))
            }
            Command::StopOn(div, idx) => {
                stop_state |= 1 << 16 * div as u8 + idx;
                LATEST_STOP_STATE.signal(stop_state);
                Some(Event::StopOn(div, idx))
            }
            Command::StopToggle(div, idx) => {
                let shift = 16 * div as u8 + idx;
                stop_state ^= 1 << shift;
                LATEST_STOP_STATE.signal(stop_state);
                if stop_state >> shift & 1 == 1 {
                    Some(Event::StopOn(div, idx))
                } else {
                    Some(Event::StopOff(div, idx))
                }
            }
            Command::GeneralCancel() => {
                stop_state = 0;
                LATEST_STOP_STATE.signal(stop_state);
                Some(Event::GeneralCancel())
            }
            Command::RecallPreset(idx) => {
                if awaiting_save {
                    // Saving a preset is internal; it emits no events.
                    preset_store.save(idx, &stop_state).await;
                    // Safety: Disengage save mode if we've already written one preset.
                    awaiting_save = false;
                    None
                } else {
                    stop_state = preset_store.load(idx).await;
                    LATEST_STOP_STATE.signal(stop_state);
                    Some(Event::PresetRecalled(idx, stop_state))
                }
            }
            Command::EnableSave(val) => {
                awaiting_save = val;
                None
            }
            Command::Expression(div, value) => Some(Event::Expression(div, value)),
            Command::Crescendo(value) => Some(Event::Crescendo(value)),
        };

        if let Some(e) = event {
            if src == CommandSource::Local {
                let _ = USB_EVENTS.try_send(e);
            }
            UART_EVENTS.send(e).await;
        }
    }
}

#[embassy_executor::main]
async fn main(spawner: Spawner) {
    let p = embassy_rp::init(Default::default());

    let i2c = embassy_rp::i2c::I2c::new_blocking(p.I2C0, p.PIN_5, p.PIN_4, i2c::Config::default());
    static I2C_BUS: StaticCell<I2c0Bus> = StaticCell::new();
    let i2c_bus = I2C_BUS.init(Mutex::new(i2c.into()));

    spawner
        .spawn(main_event_handler(
            PRESET_STORE.init(PresetStore::new(Flash::new(p.FLASH, p.DMA_CH0))),
        ))
        .unwrap();

    static TX_BUF: StaticCell<[u8; 16]> = StaticCell::new();
    let tx_buf = &mut TX_BUF.init([0; 16])[..];
    static RX_BUF: StaticCell<[u8; 16]> = StaticCell::new();
    let rx_buf = &mut RX_BUF.init([0; 16])[..];
    let uart_txrx = uart::BufferedUart::new(
        p.UART0,
        p.PIN_16,
        p.PIN_17,
        Irqs,
        tx_buf,
        rx_buf,
        uart::Config::default(),
    );
    let (uart_tx, uart_rx) = uart_txrx.split();
    spawner.spawn(uart_reader(uart_rx)).unwrap();
    spawner.spawn(uart_writer(uart_tx)).unwrap();

    setup_mcps(i2c_bus);
    spawner.spawn(scan_stop_tab_buttons(i2c_bus)).unwrap();
    spawner.spawn(write_stop_state_to_leds(i2c_bus)).unwrap();
    spawner
        .spawn(scan_pistons(
            p.PIN_11.into(),
            p.PIN_12.into(),
            p.PIN_13.into(),
        ))
        .unwrap();
    spawner.spawn(usb_midi(spawner, p.USB)).unwrap();

    defmt::info!("All tasks spawned.");

    // Heartbeat task comes last, and happens on the main loop, roughly indicating that all tasks spawned successfully.
    let mut led = Output::new(p.PIN_25, Level::Low);

    loop {
        led.toggle();
        Timer::after_secs(1).await;
    }
}
