#![no_std]
#![no_main]

mod mcp23017;
mod presets;

use core::cell::RefCell;

use embassy_embedded_hal::shared_bus::blocking::i2c::I2cDevice;
use embassy_executor::Spawner;
use embassy_rp::flash::Flash;
use embassy_rp::gpio::Pull;
use embassy_rp::peripherals::{I2C0, UART0, USB};
use embassy_rp::{
    Peri,
    gpio::{AnyPin, Input, Level, Output},
};
use embassy_rp::{bind_interrupts, i2c};
use embassy_rp::{uart, usb};
use embassy_sync::blocking_mutex::Mutex;
use embassy_sync::blocking_mutex::raw::{CriticalSectionRawMutex, NoopRawMutex};
use embassy_sync::channel::Channel;
use embassy_sync::signal::Signal;
use embassy_time::Timer;
use embassy_usb::class::midi::MidiClass;
use embassy_usb::{Builder, Config as UsbConfig};
use epworth_organ::Division;
use epworth_organ::command::{Command, CommandSource};
use epworth_organ::debouncer::Debouncer;
use epworth_organ::event::Event;
use panic_halt as _;
use static_cell::{ConstStaticCell, StaticCell};

use crate::mcp23017::MCP23017;
use crate::mcp23017::Port;
use crate::presets::PresetStore;

type I2c0Bus = Mutex<NoopRawMutex, RefCell<i2c::I2c<'static, I2C0, i2c::Blocking>>>;
type I2c0Mcp = MCP23017<I2cDevice<'static, NoopRawMutex, i2c::I2c<'static, I2C0, i2c::Blocking>>>;

bind_interrupts!(struct Irqs {
    USBCTRL_IRQ => usb::InterruptHandler<USB>;
    UART0_IRQ => uart::InterruptHandler<UART0>;
});

const MCP_I2C_ADDRESSES: [[u8; 2]; 4] = [[0x20, 0x21], [0x22, 0x23], [0x24, 0x25], [0x26, 0x27]];
const DIVISIONS: [Division; 4] = [
    Division::Swell,
    Division::Great,
    Division::Choir,
    Division::Pedal,
];

static LATEST_STOP_STATE: Signal<CriticalSectionRawMutex, u64> = Signal::new();
static PRESET_STORE: StaticCell<PresetStore> = StaticCell::new();

// Queue for all commands on the organ. These commands can be either generated by mechanical interactions with the
// console (e.g. pressing a stop tab button, moving an expression pedal, etc.), including mechanical interactions
// relayed to this particular MCU over UART, or they can be received over USB MIDI.
static COMMAND_BUS: Channel<CriticalSectionRawMutex, (Command, CommandSource), 128> =
    Channel::new();

// Queues for events destined for the decoders (via UART) or the computer (via USB).
static UART_EVENT_BUS: Channel<CriticalSectionRawMutex, Event, 64> = Channel::new();
static USB_EVENT_BUS: Channel<CriticalSectionRawMutex, Event, 64> = Channel::new();

static USB_CONFIG_DESCRIPTOR: ConstStaticCell<[u8; 256]> = ConstStaticCell::new([0; 256]);
static USB_BOS_DESCRIPTOR: ConstStaticCell<[u8; 256]> = ConstStaticCell::new([0; 256]);
static USB_CONTROL_BUF: ConstStaticCell<[u8; 64]> = ConstStaticCell::new([0; 64]);

fn reverse_byte(a: &u8) -> u8 {
    let mut b = *a;
    b = (b & 0xF0) >> 4 | (b & 0x0F) << 4;
    b = (b & 0xCC) >> 2 | (b & 0x33) << 2;
    b = (b & 0xAA) >> 1 | (b & 0x55) << 1;
    b
}

fn get_mcps(i2c_bus: &'static I2c0Bus) -> [[I2c0Mcp; 2]; 4] {
    MCP_I2C_ADDRESSES.map(|[addr0, addr1]| {
        [
            MCP23017::new(I2cDevice::new(i2c_bus), addr0),
            MCP23017::new(I2cDevice::new(i2c_bus), addr1),
        ]
    })
}

#[embassy_executor::task]
async fn write_stop_state(i2c_bus: &'static I2c0Bus) {
    let mcp_pairs = &mut get_mcps(i2c_bus);

    loop {
        // Only update when things have changed.
        let mut stop_state: u64 = LATEST_STOP_STATE.wait().await;

        // This is our approach to batching lots of little changes: Wait for a brief interval before reading the stop
        // states again.
        Timer::after_millis(1).await;

        stop_state = LATEST_STOP_STATE.try_take().unwrap_or(stop_state);

        for (mcp_pair, div) in mcp_pairs.iter_mut().zip(DIVISIONS) {
            let state = stop_state >> (16 * div as u8) & 0xFFFF;
            let left_half = reverse_byte(&(!(state >> 8) as u8));
            let right_half = reverse_byte(&(!(state & 0xFF) as u8));
            mcp_pair[0]
                .write_gpio(Port::GPIOA, (left_half & 0x7F) << 1)
                .unwrap();
            mcp_pair[0]
                .write_gpio(Port::GPIOB, left_half & 0x80)
                .unwrap();
            mcp_pair[1]
                .write_gpio(Port::GPIOA, right_half & 0x7F)
                .unwrap();
        }
    }
}

#[embassy_executor::task]
async fn scan_stop_tab_buttons(i2c_bus: &'static I2c0Bus) {
    let mut mcp_pairs = get_mcps(i2c_bus);
    let mut stop_tab_button_debouncers: [Debouncer<5>; 4] = [
        Debouncer::<5>::new(0xFFFF),
        Debouncer::<5>::new(0xFFFF),
        Debouncer::<5>::new(0xFFFF),
        Debouncer::<5>::new(0xFFFF),
    ];

    loop {
        for (mcp_pair, div) in mcp_pairs.iter_mut().zip(DIVISIONS) {
            let mut raw_reading = 0x01u16; // LSB always 1, by convention
            raw_reading |= ((mcp_pair[0].read_gpio(Port::GPIOA).unwrap() & 0x01) as u16) << 8;
            raw_reading |= ((mcp_pair[0].read_gpio(Port::GPIOB).unwrap() & 0x7F) as u16) << 9;
            raw_reading |= ((mcp_pair[1].read_gpio(Port::GPIOB).unwrap() & 0x7F) as u16) << 1;
            stop_tab_button_debouncers[div as usize].update(raw_reading);

            for i in stop_tab_button_debouncers[div as usize].falling_edges() {
                COMMAND_BUS
                    .send((Command::StopToggle(div, i), CommandSource::Local))
                    .await;
            }
        }
        Timer::after_micros(200).await;
    }
}

#[embassy_executor::task]
async fn scan_pistons(
    load_pin: Peri<'static, AnyPin>,
    clock_pin: Peri<'static, AnyPin>,
    data_pin: Peri<'static, AnyPin>,
) {
    let mut piston_debouncer = Debouncer::<5>::new(0xFFFF);

    // Load piston states into 74HC165 shift register
    let mut piston_load_pin = Output::new(load_pin, Level::Low);
    let mut piston_clock_pin = Output::new(clock_pin, Level::Low);
    let piston_data_pin = Input::new(data_pin, Pull::Up);

    loop {
        piston_load_pin.set_low();
        piston_load_pin.set_high();

        let mut raw_piston_reading = 0u16;
        // Ensure clock pin low first...
        piston_clock_pin.set_low();

        // ...then clock the data into the piston readings.
        for i in 0..8 {
            if piston_data_pin.is_high() {
                raw_piston_reading |= 1 << i;
            }
            piston_clock_pin.set_high();
            piston_clock_pin.set_low();
        }
        // Nothing is hooked up to 8-15 right now...
        raw_piston_reading |= 0xFF00;

        piston_debouncer.update(raw_piston_reading);

        for i in piston_debouncer.falling_edges() {
            if i == 0 {
                COMMAND_BUS
                    .send((Command::EnableSave(true), CommandSource::Local))
                    .await;
            } else if i == 1 {
                COMMAND_BUS
                    .send((Command::GeneralCancel(), CommandSource::Local))
                    .await;
            } else {
                COMMAND_BUS
                    .send((Command::RecallPreset(i), CommandSource::Local))
                    .await;
            }
        }

        for i in piston_debouncer.rising_edges() {
            if i == 0 {
                COMMAND_BUS
                    .send((Command::EnableSave(false), CommandSource::Local))
                    .await;
            }
        }

        Timer::after_micros(200).await;
    }
}

#[embassy_executor::task]
async fn run_usb_device(
    mut usb_device: embassy_usb::UsbDevice<'static, usb::Driver<'static, USB>>,
) {
    usb_device.run().await;
}

#[embassy_executor::task]
async fn usb_midi(spawner: Spawner, usb: Peri<'static, USB>) {
    let driver = usb::Driver::new(usb, Irqs);
    let mut config = UsbConfig::new(0xc0de, 0xcafe);
    config.manufacturer = Some("RP Pico 2");
    config.product = Some("Epworth Organ MIDI");
    config.serial_number = Some("12345678");
    config.max_power = 100;
    config.max_packet_size_0 = 64;

    let mut builder = Builder::new(
        driver,
        config,
        USB_CONFIG_DESCRIPTOR.take(),
        USB_BOS_DESCRIPTOR.take(),
        &mut [], // no msos descriptors
        USB_CONTROL_BUF.take(),
    );

    let mut midi_class = MidiClass::new(&mut builder, 1, 1, 64);

    // Build the builder.
    let usb_device = builder.build();

    // Run the USB device forever, in a separate task.
    spawner.spawn(run_usb_device(usb_device)).unwrap();

    midi_class.wait_connection().await;

    loop {
        let event = USB_EVENT_BUS.receive().await;
        for packet in event.to_usb_midi_packets() {
            let _ = midi_class.write_packet(&packet).await;
        }
    }
}

#[embassy_executor::task]
async fn uart_reader(mut uart_rx: uart::UartRx<'static, uart::Async>) {
    loop {
        // All events on UART are proprietary 2-byte messages, as defined in the Event struct.
        let mut buf: [u8; 2] = [0; 2];

        match uart_rx.read(&mut buf).await {
            Ok(_) => {
                // TODO
                // COMMAND_BUS
                //     .send(EventIn(EventSource::Local, Event::parse(buf[0], buf[1])))
                //     .await;
            }
            Err(e) => {
                defmt::warn!("Error reading from UART: {:?}", e);
            }
        }
    }
}

#[embassy_executor::task]
async fn uart_writer(mut _uart_tx: uart::UartTx<'static, uart::Async>) {
    loop {
        let _ = UART_EVENT_BUS.receive().await;
    }
}

fn setup_mcps(i2c_bus: &'static I2c0Bus) {
    for mcp_pair in get_mcps(i2c_bus).iter_mut() {
        mcp_pair[0].init_hardware().unwrap();
        mcp_pair[1].init_hardware().unwrap();
        // Set pin modes (input/output) for MCP23017s based on the schematic
        mcp_pair[0].port_mode(Port::GPIOA, 0x01).unwrap();
        mcp_pair[0].port_mode(Port::GPIOB, 0x7F).unwrap();
        mcp_pair[1].port_mode(Port::GPIOA, 0x00).unwrap();
        mcp_pair[1].port_mode(Port::GPIOB, 0x7F).unwrap();
        // Write all outputs high, inputs low.
        mcp_pair[0].write_gpio(Port::GPIOA, 0xFE).unwrap();
        mcp_pair[0].write_gpio(Port::GPIOB, 0x80).unwrap();
        mcp_pair[1].write_gpio(Port::GPIOA, 0x7F).unwrap();
        mcp_pair[1].write_gpio(Port::GPIOB, 0x00).unwrap();
    }
}

#[embassy_executor::task]
async fn main_event_handler(preset_store: &'static mut PresetStore<'static>) {
    let mut stop_state: u64 = 0u64;
    let mut awaiting_save = false;

    // Flush initial stop state.
    LATEST_STOP_STATE.signal(stop_state);

    loop {
        let (command, src) = COMMAND_BUS.receive().await;

        // TODO: Should we make this pub/sub? I notice we're always enqueueing on 2 event buses.
        match command {
            Command::StopToggle(div, idx) => {
                let shift = 16 * div as u8 + idx;
                stop_state ^= 1 << shift;
                LATEST_STOP_STATE.signal(stop_state);
                let ev = if stop_state >> shift & 1 == 1 {
                    Event::StopOn(div, idx)
                } else {
                    Event::StopOff(div, idx)
                };
                UART_EVENT_BUS.send(ev).await;
                if src == CommandSource::Local {
                    let _ = USB_EVENT_BUS.try_send(ev);
                }
            }
            Command::GeneralCancel() => {
                stop_state = 0;
                LATEST_STOP_STATE.signal(stop_state);
                let ev = Event::GeneralCancel();
                UART_EVENT_BUS.send(ev).await;
                if src == CommandSource::Local {
                    let _ = USB_EVENT_BUS.try_send(ev);
                }
            }
            Command::RecallPreset(idx) => {
                if awaiting_save {
                    // Saving a preset is internal; it emits no events.
                    preset_store.save(idx, &stop_state).await;
                    // Safety: Disengage save mode if we've already written one preset.
                    awaiting_save = false;
                } else {
                    stop_state = preset_store.load(idx).await;
                    LATEST_STOP_STATE.signal(stop_state);
                    let recall_ev = Event::PresetRecalled(idx);
                    let ssc_ev = Event::StopStateChanged(stop_state);
                    UART_EVENT_BUS.send(recall_ev).await;
                    UART_EVENT_BUS.send(ssc_ev).await;
                    if src == CommandSource::Local {
                        let _ = USB_EVENT_BUS.try_send(recall_ev);
                        let _ = USB_EVENT_BUS.try_send(ssc_ev);
                    }
                }
            }
            Command::EnableSave(val) => {
                awaiting_save = val;
            }
            _ => {}
        };
    }
}

#[embassy_executor::main]
async fn main(spawner: Spawner) {
    let p = embassy_rp::init(Default::default());

    let i2c = embassy_rp::i2c::I2c::new_blocking(p.I2C0, p.PIN_5, p.PIN_4, i2c::Config::default());
    static I2C_BUS: StaticCell<I2c0Bus> = StaticCell::new();
    let i2c_bus = I2C_BUS.init(Mutex::new(i2c.into()));

    spawner
        .spawn(main_event_handler(
            PRESET_STORE.init(PresetStore::new(Flash::new(p.FLASH, p.DMA_CH2))),
        ))
        .unwrap();

    let uart_txrx = uart::Uart::new(
        p.UART0,
        p.PIN_16,
        p.PIN_17,
        Irqs,
        p.DMA_CH0,
        p.DMA_CH1,
        uart::Config::default(),
    );
    let (uart_tx, uart_rx) = uart_txrx.split();
    spawner.spawn(uart_reader(uart_rx)).unwrap();
    spawner.spawn(uart_writer(uart_tx)).unwrap();

    setup_mcps(i2c_bus);
    spawner.spawn(scan_stop_tab_buttons(i2c_bus)).unwrap();
    spawner.spawn(write_stop_state(i2c_bus)).unwrap();
    spawner
        .spawn(scan_pistons(
            p.PIN_11.into(),
            p.PIN_12.into(),
            p.PIN_13.into(),
        ))
        .unwrap();
    spawner.spawn(usb_midi(spawner, p.USB)).unwrap();

    // Heartbeat task comes last, and happens on the main loop, roughly indicating that all tasks spawned successfully.
    let mut led = Output::new(p.PIN_25, Level::Low);

    loop {
        led.toggle();
        Timer::after_secs(1).await;
    }
}
